<a href="https://colab.research.google.com/github/bhupendradhami/colab/blob/main/Lab1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Q1. Write a Python program to display the current date and time. 


In [30]:
import datetime as dt
now=dt.datetime.now()
print("Current date & time : "+now.strftime("%Y-%m-%d %H:%M:%S"))

Current date & time : 2023-04-09 06:52:55


###Q2. Write a Python program that calculates the area of a circle based on the radius entered by the user

In [31]:
from math import pi
r=float(input("Enter the radius: "))
a=pi*r**2
ans=round(a,2)
print("Area of the circle is: "+str(a))
print("Area of the circle is: "+str(ans))

Enter the radius: 4
Area of the circle is: 50.26548245743669
Area of the circle is: 50.27


###Q3. Write a Python program that accepts the user's first and last name and prints them in reverse order with a space between them.

In [32]:
fname = input("Input your First Name : ")
lname = input("Input your Last Name : ")
print ("Hello " + lname + " " + fname)

Input your First Name : Bhuppi
Input your Last Name : Dhami
Hello Dhami Bhuppi


###Q4. Write a Python program to display the first and last colors from the following list. 

In [33]:
color_list = ["Red","Green","White" ,"Black"]
color_list = ["Red","Green","White" ,"Black"]
print( "%s %s"%(color_list[0],color_list[-1]))

Red Black


###Q5. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.

In [34]:
a = int(input("Input an integer : "))
n1 = int( "%s" % a )
n2 = int( "%s%s" % (a,a) )
n3 = int( "%s%s%s" % (a,a,a) )
print (n1+n2+n3)

Input an integer : 4
492


###Q6. Create a Numpy array object

In [35]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


###Q7. Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6

In [36]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


###Q8.Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:


In [37]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


###Q9. Check the dimensions of the arrays

In [38]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


###Q10. Access the element on the first row, second column:

In [39]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


###Q11. Access the element on the 2nd row, 5th column:

In [40]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


###Q12. Descriptive Analysis

In [42]:
import scipy as sp
import numpy as np
nums=np.random.randint(1,20,size=(1,18))[0]
print("Data :", nums)
print("Get Descriptive Statistics")
print("Mean :",np.mean(nums))
print("Median :",np.median(nums))
from scipy import stats, optimize, interpolate
print("Mode :",sp.stats.mode(nums,keepdims=True))
print('Standard Deviation :',np.std(nums))
print('Variance :',np.var(nums))
print('Skew :',sp.stats.skew(nums))
print('Kurtosis :',sp.stats.kurtosis(nums))

Data : [11  7 12 13 17 16 17  9  2 13  3  8  7  7 18 18 18 16]
get descriptive stats
Mean : 11.777777777777779
Median : 12.5
Mode : ModeResult(mode=array([7]), count=array([3]))
Standard Deviation : 5.126787553359701
Variance : 26.28395061728395
Skew : -0.35142484023194304
Kurtosis : -1.107948765410717
